name = "mitch-app"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./dist", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "mitch-app-db"
database_id = "ee4ba7ec-97c4-4c6b-9f39-72f142b935ef"

[[r2_buckets]]
binding = "R2"
bucket_name = "mitch-app-files"

[vars]
ENVIRONMENT = "development"

[dev]
port = 8787
